// Package service 走失人员应用服务测试
package service

import (
	"testing"
	"time"

	"github.com/Snowitty-Re/CNtunyuan/internal/application/dto"
	"github.com/Snowitty-Re/CNtunyuan/internal/domain/entity"
	"github.com/Snowitty-Re/CNtunyuan/internal/infrastructure/repository"
	"github.com/Snowitty-Re/CNtunyuan/internal/testutil"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func setupMissingPersonTest(t *testing.T) (*MissingPersonAppService, *testutil.TestDB) {
	tdb := testutil.NewTestDB(t)
	mpRepo := repository.NewMissingPersonRepository(tdb.DB)
	service := NewMissingPersonAppService(mpRepo, nil)
	return service, tdb
}

func TestMissingPersonAppService_Create(t *testing.T) {
	service, tdb := setupMissingPersonTest(t)
	defer tdb.Close()

	// 创建测试组织
	org := &entity.Organization{
		BaseEntity: entity.BaseEntity{ID: "test-org-id"},
		Name:       "测试组织",
		Code:       "TEST001",
		Type:       entity.OrgTypeCity,
	}
	testutil.MustCreate(t, tdb.DB, org)

	// 创建报告人
	reporter := &entity.User{
		BaseEntity: entity.BaseEntity{ID: "reporter-id"},
		Nickname:   "报告人",
		Phone:      "13800138000",
		Email:      "reporter@test.com",
		Role:       entity.RoleVolunteer,
		Status:     entity.UserStatusActive,
		OrgID:      org.ID,
	}
	reporter.SetPassword("password123")
	testutil.MustCreate(t, tdb.DB, reporter)

	birthDate := time.Date(1990, 1, 1, 0, 0, 0, 0, time.UTC)
	missingTime := time.Date(2024, 1, 15, 10, 0, 0, 0, time.UTC)

	tests := []struct {
		name         string
		req          *dto.CreateMissingPersonRequest
		reporterID   string
		orgID        string
		wantErr      bool
		expectedResp func(t *testing.T, resp *dto.MissingPersonResponse)
	}{
		{
			name: "create with valid data",
			req: &dto.CreateMissingPersonRequest{
				Name:         "张三",
				Gender:       "male",
				BirthDate:    birthDate,
				Age:          34,
				Height:       175,
				Weight:       70,
				Description:  "走失人员描述",
				PhotoUrl:     "http://example.com/photo.jpg",
				MissingTime:  missingTime,
				Province:     "广东省",
				City:         "深圳市",
				District:     "南山区",
				Address:      "科技园",
				Clothes:      "蓝色T恤",
				Features:     "脸上有痣",
				ContactName:  "李四",
				ContactPhone: "13900139000",
				ContactRel:   "父亲",
				AltContact:   "13800138001",
				UrgencyLevel: "high",
			},
			reporterID: reporter.ID,
			orgID:      org.ID,
			wantErr:    false,
			expectedResp: func(t *testing.T, resp *dto.MissingPersonResponse) {
				assert.NotEmpty(t, resp.ID)
				// Note: CaseNo is generated by the entity layer, may be empty in response
				// depending on implementation
				assert.Equal(t, "张三", resp.Name)
				assert.Equal(t, "male", resp.Gender)
				assert.Equal(t, 34, resp.Age)
				assert.Equal(t, 175, resp.Height)
				assert.Equal(t, 70, resp.Weight)
				assert.Equal(t, "走失人员描述", resp.Description)
				assert.Equal(t, "广东省", resp.Province)
				assert.Equal(t, "深圳市", resp.City)
				assert.Equal(t, "南山区", resp.District)
				assert.Equal(t, "李四", resp.ContactName)
				assert.Equal(t, "13900139000", resp.ContactPhone)
				assert.Equal(t, string(entity.MissingStatusMissing), resp.Status)
				assert.Equal(t, string(entity.UrgencyLevelHigh), resp.UrgencyLevel)
				assert.Equal(t, reporter.ID, resp.ReporterID)
				assert.Equal(t, org.ID, resp.OrgID)
			},
		},
		{
			name: "create with low urgency level",
			req: &dto.CreateMissingPersonRequest{
				Name:         "王五",
				Gender:       "female",
				BirthDate:    birthDate,
				Age:          28,
				MissingTime:  missingTime.Add(-24 * time.Hour), // Different day to avoid case_no collision
				Province:     "北京市",
				City:         "北京市",
				ContactName:  "赵六",
				ContactPhone: "13700137000",
				UrgencyLevel: "low",
			},
			reporterID: reporter.ID,
			orgID:      org.ID,
			wantErr:    false,
			expectedResp: func(t *testing.T, resp *dto.MissingPersonResponse) {
				assert.Equal(t, "王五", resp.Name)
				assert.Equal(t, string(entity.UrgencyLevelLow), resp.UrgencyLevel)
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			resp, err := service.Create(testutil.Context(), tt.req, tt.reporterID, tt.orgID)
			if tt.wantErr {
				assert.Error(t, err)
				return
			}
			require.NoError(t, err)
			require.NotNil(t, resp)
			tt.expectedResp(t, resp)
		})
	}
}

func TestMissingPersonAppService_GetByID(t *testing.T) {
	service, tdb := setupMissingPersonTest(t)
	defer tdb.Close()

	// 创建测试数据
	org := &entity.Organization{
		BaseEntity: entity.BaseEntity{ID: "test-org-id"},
		Name:       "测试组织",
		Code:       "TEST001",
		Type:       entity.OrgTypeCity,
	}
	testutil.MustCreate(t, tdb.DB, org)

	reporter := &entity.User{
		BaseEntity: entity.BaseEntity{ID: "reporter-id"},
		Nickname:   "报告人",
		Phone:      "13800138000",
		Role:       entity.RoleVolunteer,
		Status:     entity.UserStatusActive,
		OrgID:      org.ID,
	}
	reporter.SetPassword("password123")
	testutil.MustCreate(t, tdb.DB, reporter)

	// 创建走失人员
	mp := &entity.MissingPerson{
		BaseEntity:   entity.BaseEntity{ID: "mp-id-1"},
		CaseNo:       "CASE-20240101-0001",
		Name:         "测试走失者",
		Gender:       "male",
		Age:          30,
		Description:  "测试描述",
		MissingTime:  time.Now(),
		Province:     "广东省",
		City:         "深圳市",
		ContactName:  "联系人",
		ContactPhone: "13900139000",
		ReporterID:   reporter.ID,
		OrgID:        org.ID,
		Status:       entity.MissingStatusMissing,
		Urgency:      entity.UrgencyLevelHigh,
		Views:        10,
	}
	testutil.MustCreate(t, tdb.DB, mp)

	tests := []struct {
		name    string
		id      string
		wantErr bool
		errMsg  string
	}{
		{
			name:    "existing missing person",
			id:      mp.ID,
			wantErr: false,
		},
		{
			name:    "non-existing missing person",
			id:      "non-existing-id",
			wantErr: true,
			errMsg:  "not found",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			resp, err := service.GetByID(testutil.Context(), tt.id)
			if tt.wantErr {
				assert.Error(t, err)
				assert.ErrorIs(t, err, ErrMissingPersonNotFound)
				return
			}
			require.NoError(t, err)
			require.NotNil(t, resp)
			assert.Equal(t, mp.ID, resp.ID)
			assert.Equal(t, mp.Name, resp.Name)
			assert.Equal(t, mp.CaseNo, resp.CaseNo)
			assert.Equal(t, string(mp.Status), resp.Status)
		})
	}
}

func TestMissingPersonAppService_List(t *testing.T) {
	service, tdb := setupMissingPersonTest(t)
	defer tdb.Close()

	// 创建测试组织
	org := &entity.Organization{
		BaseEntity: entity.BaseEntity{ID: "test-org-id"},
		Name:       "测试组织",
		Code:       "TEST001",
		Type:       entity.OrgTypeCity,
	}
	testutil.MustCreate(t, tdb.DB, org)

	reporter := &entity.User{
		BaseEntity: entity.BaseEntity{ID: "reporter-id"},
		Nickname:   "报告人",
		Phone:      "13800138000",
		Role:       entity.RoleVolunteer,
		Status:     entity.UserStatusActive,
		OrgID:      org.ID,
	}
	reporter.SetPassword("password123")
	testutil.MustCreate(t, tdb.DB, reporter)

	// 创建多个走失人员
	persons := []*entity.MissingPerson{
		{
			BaseEntity:   entity.BaseEntity{ID: "mp-1"},
			CaseNo:       "CASE-20240101-0001",
			Name:         "张三",
			Gender:       "male",
			Age:          25,
			MissingTime:  time.Now(),
			Province:     "广东省",
			City:         "深圳市",
			ContactName:  "联系人1",
			ContactPhone: "13900139001",
			ReporterID:   reporter.ID,
			OrgID:        org.ID,
			Status:       entity.MissingStatusMissing,
			Urgency:      entity.UrgencyLevelCritical,
		},
		{
			BaseEntity:   entity.BaseEntity{ID: "mp-2"},
			CaseNo:       "CASE-20240101-0002",
			Name:         "李四",
			Gender:       "female",
			Age:          30,
			MissingTime:  time.Now(),
			Province:     "广东省",
			City:         "广州市",
			ContactName:  "联系人2",
			ContactPhone: "13900139002",
			ReporterID:   reporter.ID,
			OrgID:        org.ID,
			Status:       entity.MissingStatusSearching,
			Urgency:      entity.UrgencyLevelHigh,
		},
		{
			BaseEntity:   entity.BaseEntity{ID: "mp-3"},
			CaseNo:       "CASE-20240101-0003",
			Name:         "王五",
			Gender:       "male",
			Age:          35,
			MissingTime:  time.Now(),
			Province:     "北京市",
			City:         "北京市",
			ContactName:  "联系人3",
			ContactPhone: "13900139003",
			ReporterID:   reporter.ID,
			OrgID:        org.ID,
			Status:       entity.MissingStatusFound,
			Urgency:      entity.UrgencyLevelMedium,
		},
	}

	for _, p := range persons {
		testutil.MustCreate(t, tdb.DB, p)
	}

	tests := []struct {
		name         string
		req          *dto.MissingPersonListRequest
		expectedLen  int
		expectedName string
	}{
		{
			name: "list all without filters",
			req: &dto.MissingPersonListRequest{
				Page:     1,
				PageSize: 10,
			},
			expectedLen: 3,
		},
		{
			name: "filter by status - missing",
			req: &dto.MissingPersonListRequest{
				Page:     1,
				PageSize: 10,
				Status:   string(entity.MissingStatusMissing),
			},
			expectedLen:  1,
			expectedName: "张三",
		},
		{
			name: "filter by status - searching",
			req: &dto.MissingPersonListRequest{
				Page:     1,
				PageSize: 10,
				Status:   string(entity.MissingStatusSearching),
			},
			expectedLen:  1,
			expectedName: "李四",
		},
		{
			name: "filter by location - Guangzhou",
			req: &dto.MissingPersonListRequest{
				Page:     1,
				PageSize: 10,
				City:     "广州市",
			},
			expectedLen:  1,
			expectedName: "李四",
		},
		{
			name: "filter by location - Guangdong Province",
			req: &dto.MissingPersonListRequest{
				Page:     1,
				PageSize: 10,
				Province: "广东省",
			},
			expectedLen: 2,
		},
		{
			name: "filter by urgency level - critical",
			req: &dto.MissingPersonListRequest{
				Page:         1,
				PageSize:     10,
				UrgencyLevel: string(entity.UrgencyLevelCritical),
			},
			expectedLen:  1,
			expectedName: "张三",
		},
		{
			name: "filter by gender - male",
			req: &dto.MissingPersonListRequest{
				Page:     1,
				PageSize: 10,
				Gender:   "male",
			},
			expectedLen: 2,
		},
		{
			name: "filter by age range",
			req: &dto.MissingPersonListRequest{
				Page:     1,
				PageSize: 10,
				AgeMin:   28,
				AgeMax:   32,
			},
			expectedLen:  1,
			expectedName: "李四",
		},
		{
			name: "filter by keyword",
			req: &dto.MissingPersonListRequest{
				Page:     1,
				PageSize: 10,
				Keyword:  "张三",
			},
			expectedLen:  1,
			expectedName: "张三",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			resp, err := service.List(testutil.Context(), tt.req)
			require.NoError(t, err)
			require.NotNil(t, resp)
			assert.Equal(t, tt.expectedLen, len(resp.List))
			if tt.expectedName != "" && len(resp.List) > 0 {
				assert.Equal(t, tt.expectedName, resp.List[0].Name)
			}
		})
	}
}

func TestMissingPersonAppService_Update(t *testing.T) {
	service, tdb := setupMissingPersonTest(t)
	defer tdb.Close()

	// 创建测试数据
	org := &entity.Organization{
		BaseEntity: entity.BaseEntity{ID: "test-org-id"},
		Name:       "测试组织",
		Code:       "TEST001",
		Type:       entity.OrgTypeCity,
	}
	testutil.MustCreate(t, tdb.DB, org)

	reporter := &entity.User{
		BaseEntity: entity.BaseEntity{ID: "reporter-id"},
		Nickname:   "报告人",
		Phone:      "13800138000",
		Role:       entity.RoleVolunteer,
		Status:     entity.UserStatusActive,
		OrgID:      org.ID,
	}
	reporter.SetPassword("password123")
	testutil.MustCreate(t, tdb.DB, reporter)

	birthDate := time.Date(1990, 1, 1, 0, 0, 0, 0, time.UTC)

	// 创建走失人员
	mp := &entity.MissingPerson{
		BaseEntity:   entity.BaseEntity{ID: "mp-id-1"},
		CaseNo:       "CASE-20240101-0001",
		Name:         "原姓名",
		Gender:       "male",
		BirthDate:    &birthDate,
		Age:          30,
		Height:       170,
		Weight:       65,
		Description:  "原描述",
		MissingTime:  time.Now(),
		Province:     "广东省",
		City:         "深圳市",
		Address:      "原地址",
		Clothes:      "原衣着",
		Features:     "原特征",
		ContactName:  "原联系人",
		ContactPhone: "13900139000",
		ContactRel:   "父亲",
		AltContact:   "13800138000",
		ReporterID:   reporter.ID,
		OrgID:        org.ID,
		Status:       entity.MissingStatusMissing,
		Urgency:      entity.UrgencyLevelMedium,
	}
	testutil.MustCreate(t, tdb.DB, mp)

	newBirthDate := time.Date(1991, 2, 2, 0, 0, 0, 0, time.UTC)
	newMissingTime := time.Date(2024, 2, 1, 10, 0, 0, 0, time.UTC)

	tests := []struct {
		name         string
		id           string
		req          *dto.UpdateMissingPersonRequest
		expectedResp func(t *testing.T, resp *dto.MissingPersonResponse)
		wantErr      bool
		errMsg       string
	}{
		{
			name: "update all fields",
			id:   mp.ID,
			req: &dto.UpdateMissingPersonRequest{
				Name:         "新姓名",
				Gender:       "female",
				BirthDate:    newBirthDate,
				Age:          35,
				Height:       175,
				Weight:       70,
				Description:  "新描述",
				PhotoUrl:     "http://example.com/new-photo.jpg",
				MissingTime:  newMissingTime,
				Province:     "北京市",
				City:         "北京市",
				District:     "朝阳区",
				Address:      "新地址",
				Clothes:      "新衣着",
				Features:     "新特征",
				ContactName:  "新联系人",
				ContactPhone: "13900139111",
				ContactRel:   "母亲",
				AltContact:   "13800138111",
				UrgencyLevel: "high",
			},
			expectedResp: func(t *testing.T, resp *dto.MissingPersonResponse) {
				assert.Equal(t, "新姓名", resp.Name)
				assert.Equal(t, "female", resp.Gender)
				assert.Equal(t, 35, resp.Age)
				assert.Equal(t, 175, resp.Height)
				assert.Equal(t, 70, resp.Weight)
				assert.Equal(t, "新描述", resp.Description)
				assert.Equal(t, "北京市", resp.Province)
				assert.Equal(t, "朝阳区", resp.District)
				assert.Equal(t, "新联系人", resp.ContactName)
				assert.Equal(t, "13900139111", resp.ContactPhone)
				assert.Equal(t, string(entity.UrgencyLevelHigh), resp.UrgencyLevel)
			},
			wantErr: false,
		},
		{
			name: "update partial fields",
			id:   mp.ID,
			req: &dto.UpdateMissingPersonRequest{
				Name: "部分更新姓名",
				Age:  40,
			},
			expectedResp: func(t *testing.T, resp *dto.MissingPersonResponse) {
				assert.Equal(t, "部分更新姓名", resp.Name)
				assert.Equal(t, 40, resp.Age)
			},
			wantErr: false,
		},
		{
			name: "update non-existing missing person",
			id:   "non-existing-id",
			req: &dto.UpdateMissingPersonRequest{
				Name: "新姓名",
			},
			wantErr: true,
			errMsg:  "not found",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			resp, err := service.Update(testutil.Context(), tt.id, tt.req, reporter)
			if tt.wantErr {
				assert.Error(t, err)
				assert.ErrorIs(t, err, ErrMissingPersonNotFound)
				return
			}
			require.NoError(t, err)
			require.NotNil(t, resp)
			tt.expectedResp(t, resp)
		})
	}
}

func TestMissingPersonAppService_UpdateStatus(t *testing.T) {
	service, tdb := setupMissingPersonTest(t)
	defer tdb.Close()

	// 创建测试数据
	org := &entity.Organization{
		BaseEntity: entity.BaseEntity{ID: "test-org-id"},
		Name:       "测试组织",
		Code:       "TEST001",
		Type:       entity.OrgTypeCity,
	}
	testutil.MustCreate(t, tdb.DB, org)

	reporter := &entity.User{
		BaseEntity: entity.BaseEntity{ID: "reporter-id"},
		Nickname:   "报告人",
		Phone:      "13800138000",
		Role:       entity.RoleVolunteer,
		Status:     entity.UserStatusActive,
		OrgID:      org.ID,
	}
	reporter.SetPassword("password123")
	testutil.MustCreate(t, tdb.DB, reporter)

	// 创建不同状态的走失人员
	mpMissing := &entity.MissingPerson{
		BaseEntity:   entity.BaseEntity{ID: "mp-missing"},
		CaseNo:       "CASE-20240101-0001",
		Name:         "待寻找人员",
		Gender:       "male",
		MissingTime:  time.Now(),
		ContactName:  "联系人",
		ContactPhone: "13900139000",
		ReporterID:   reporter.ID,
		OrgID:        org.ID,
		Status:       entity.MissingStatusMissing,
	}
	testutil.MustCreate(t, tdb.DB, mpMissing)

	mpClosed := &entity.MissingPerson{
		BaseEntity:   entity.BaseEntity{ID: "mp-closed"},
		CaseNo:       "CASE-20240101-0002",
		Name:         "已关闭人员",
		Gender:       "female",
		MissingTime:  time.Now(),
		ContactName:  "联系人",
		ContactPhone: "13900139001",
		ReporterID:   reporter.ID,
		OrgID:        org.ID,
		Status:       entity.MissingStatusClosed,
	}
	testutil.MustCreate(t, tdb.DB, mpClosed)

	tests := []struct {
		name           string
		id             string
		status         string
		wantErr        bool
		errMsg         string
		expectedStatus entity.MissingStatus
	}{
		{
			name:           "update status from missing to searching",
			id:             mpMissing.ID,
			status:         string(entity.MissingStatusSearching),
			wantErr:        false,
			expectedStatus: entity.MissingStatusSearching,
		},
		{
			name:    "update status for non-existing person",
			id:      "non-existing-id",
			status:  string(entity.MissingStatusSearching),
			wantErr: true,
			errMsg:  "not found",
		},
		{
			name:    "update status for closed case",
			id:      mpClosed.ID,
			status:  string(entity.MissingStatusSearching),
			wantErr: true,
			errMsg:  "cannot update",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := service.UpdateStatus(testutil.Context(), tt.id, tt.status, &entity.User{
				Role:  entity.RoleManager,
				OrgID: org.ID,
			})
			if tt.wantErr {
				assert.Error(t, err)
				return
			}
			require.NoError(t, err)

			// 验证状态已更新
			var updated entity.MissingPerson
			testutil.MustFind(t, tdb.DB, &updated, "id = ?", tt.id)
			assert.Equal(t, tt.expectedStatus, updated.Status)
		})
	}
}

func TestMissingPersonAppService_Delete(t *testing.T) {
	service, tdb := setupMissingPersonTest(t)
	defer tdb.Close()

	// 创建测试数据
	org := &entity.Organization{
		BaseEntity: entity.BaseEntity{ID: "test-org-id"},
		Name:       "测试组织",
		Code:       "TEST001",
		Type:       entity.OrgTypeCity,
	}
	testutil.MustCreate(t, tdb.DB, org)

	reporter := &entity.User{
		BaseEntity: entity.BaseEntity{ID: "reporter-id"},
		Nickname:   "报告人",
		Phone:      "13800138000",
		Role:       entity.RoleVolunteer,
		Status:     entity.UserStatusActive,
		OrgID:      org.ID,
	}
	reporter.SetPassword("password123")
	testutil.MustCreate(t, tdb.DB, reporter)

	// 创建走失人员
	mp := &entity.MissingPerson{
		BaseEntity:   entity.BaseEntity{ID: "mp-to-delete"},
		CaseNo:       "CASE-20240101-0001",
		Name:         "待删除人员",
		Gender:       "male",
		MissingTime:  time.Now(),
		ContactName:  "联系人",
		ContactPhone: "13900139000",
		ReporterID:   reporter.ID,
		OrgID:        org.ID,
		Status:       entity.MissingStatusMissing,
	}
	testutil.MustCreate(t, tdb.DB, mp)

	// 验证记录存在
	var count int64
	tdb.DB.Model(&entity.MissingPerson{}).Where("id = ?", mp.ID).Count(&count)
	assert.Equal(t, int64(1), count)

	// 执行删除
	err := service.Delete(testutil.Context(), mp.ID, &entity.User{
		Role:  entity.RoleManager,
		OrgID: org.ID,
	})
	require.NoError(t, err)

	// 验证记录已被软删除（deleted_at 不为空）
	var deleted entity.MissingPerson
	err = tdb.DB.Unscoped().Where("id = ?", mp.ID).First(&deleted).Error
	require.NoError(t, err)
	assert.NotNil(t, deleted.DeletedAt)
}

func TestMissingPersonAppService_MarkFound(t *testing.T) {
	service, tdb := setupMissingPersonTest(t)
	defer tdb.Close()

	// 创建测试数据
	org := &entity.Organization{
		BaseEntity: entity.BaseEntity{ID: "test-org-id"},
		Name:       "测试组织",
		Code:       "TEST001",
		Type:       entity.OrgTypeCity,
	}
	testutil.MustCreate(t, tdb.DB, org)

	reporter := &entity.User{
		BaseEntity: entity.BaseEntity{ID: "reporter-id"},
		Nickname:   "报告人",
		Phone:      "13800138000",
		Role:       entity.RoleVolunteer,
		Status:     entity.UserStatusActive,
		OrgID:      org.ID,
	}
	reporter.SetPassword("password123")
	testutil.MustCreate(t, tdb.DB, reporter)

	// 创建走失人员
	mp := &entity.MissingPerson{
		BaseEntity:   entity.BaseEntity{ID: "mp-mark-found"},
		CaseNo:       "CASE-20240101-0001",
		Name:         "待标记找到人员",
		Gender:       "male",
		MissingTime:  time.Now(),
		ContactName:  "联系人",
		ContactPhone: "13900139000",
		ReporterID:   reporter.ID,
		OrgID:        org.ID,
		Status:       entity.MissingStatusSearching,
	}
	testutil.MustCreate(t, tdb.DB, mp)

	tests := []struct {
		name    string
		id      string
		req     *dto.MarkFoundRequest
		wantErr bool
		errMsg  string
	}{
		{
			name: "mark found successfully",
			id:   mp.ID,
			req: &dto.MarkFoundRequest{
				Location: "深圳市福田区",
				Note:     "在公园找到",
			},
			wantErr: false,
		},
		{
			name: "mark non-existing person found",
			id:   "non-existing-id",
			req: &dto.MarkFoundRequest{
				Location: "深圳市",
				Note:     "测试",
			},
			wantErr: true,
			errMsg:  "not found",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := service.MarkFound(testutil.Context(), tt.id, tt.req, &entity.User{
				Role:  entity.RoleManager,
				OrgID: org.ID,
			})
			if tt.wantErr {
				assert.Error(t, err)
				return
			}
			require.NoError(t, err)

			// 验证状态已更新
			var updated entity.MissingPerson
			testutil.MustFind(t, tdb.DB, &updated, "id = ?", tt.id)
			assert.Equal(t, entity.MissingStatusFound, updated.Status)
			assert.Equal(t, tt.req.Location, updated.FoundLocation)
			assert.Equal(t, tt.req.Note, updated.FoundNote)
			assert.NotNil(t, updated.FoundTime)
		})
	}
}

func TestMissingPersonAppService_MarkReunited(t *testing.T) {
	service, tdb := setupMissingPersonTest(t)
	defer tdb.Close()

	// 创建测试数据
	org := &entity.Organization{
		BaseEntity: entity.BaseEntity{ID: "test-org-id"},
		Name:       "测试组织",
		Code:       "TEST001",
		Type:       entity.OrgTypeCity,
	}
	testutil.MustCreate(t, tdb.DB, org)

	reporter := &entity.User{
		BaseEntity: entity.BaseEntity{ID: "reporter-id"},
		Nickname:   "报告人",
		Phone:      "13800138000",
		Role:       entity.RoleVolunteer,
		Status:     entity.UserStatusActive,
		OrgID:      org.ID,
	}
	reporter.SetPassword("password123")
	testutil.MustCreate(t, tdb.DB, reporter)

	// 创建已找到的走失人员
	foundTime := time.Now()
	mp := &entity.MissingPerson{
		BaseEntity:    entity.BaseEntity{ID: "mp-reunited"},
		CaseNo:        "CASE-20240101-0001",
		Name:          "待标记团聚人员",
		Gender:        "male",
		MissingTime:   time.Now(),
		ContactName:   "联系人",
		ContactPhone:  "13900139000",
		ReporterID:    reporter.ID,
		OrgID:         org.ID,
		Status:        entity.MissingStatusFound,
		FoundTime:     &foundTime,
		FoundLocation: "深圳市",
	}
	testutil.MustCreate(t, tdb.DB, mp)

	tests := []struct {
		name    string
		id      string
		wantErr bool
		errMsg  string
	}{
		{
			name:    "mark reunited successfully",
			id:      mp.ID,
			wantErr: false,
		},
		{
			name:    "mark non-existing person reunited",
			id:      "non-existing-id",
			wantErr: true,
			errMsg:  "not found",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := service.MarkReunited(testutil.Context(), tt.id, &entity.User{
				Role:  entity.RoleManager,
				OrgID: org.ID,
			})
			if tt.wantErr {
				assert.Error(t, err)
				return
			}
			require.NoError(t, err)

			// 验证状态已更新
			var updated entity.MissingPerson
			testutil.MustFind(t, tdb.DB, &updated, "id = ?", tt.id)
			assert.Equal(t, entity.MissingStatusReunited, updated.Status)
		})
	}
}

func TestMissingPersonAppService_AddTrack(t *testing.T) {
	service, tdb := setupMissingPersonTest(t)
	defer tdb.Close()

	// 创建测试数据
	org := &entity.Organization{
		BaseEntity: entity.BaseEntity{ID: "test-org-id"},
		Name:       "测试组织",
		Code:       "TEST001",
		Type:       entity.OrgTypeCity,
	}
	testutil.MustCreate(t, tdb.DB, org)

	reporter := &entity.User{
		BaseEntity: entity.BaseEntity{ID: "reporter-id"},
		Nickname:   "报告人",
		Phone:      "13800138000",
		Role:       entity.RoleVolunteer,
		Status:     entity.UserStatusActive,
		OrgID:      org.ID,
	}
	reporter.SetPassword("password123")
	testutil.MustCreate(t, tdb.DB, reporter)

	mp := &entity.MissingPerson{
		BaseEntity:   entity.BaseEntity{ID: "mp-track"},
		CaseNo:       "CASE-20240101-0001",
		Name:         "有轨迹人员",
		Gender:       "male",
		MissingTime:  time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		ContactName:  "联系人",
		ContactPhone: "13900139000",
		ReporterID:   reporter.ID,
		OrgID:        org.ID,
		Status:       entity.MissingStatusMissing,
	}
	testutil.MustCreate(t, tdb.DB, mp)

	trackTime := time.Date(2024, 1, 20, 14, 30, 0, 0, time.UTC)

	tests := []struct {
		name         string
		personID     string
		reporterID   string
		req          *dto.CreateMissingPersonTrackRequest
		wantErr      bool
		errMsg       string
		expectedResp func(t *testing.T, resp *dto.MissingPersonTrackResponse)
	}{
		{
			name:       "add track successfully",
			personID:   mp.ID,
			reporterID: reporter.ID,
			req: &dto.CreateMissingPersonTrackRequest{
				Location:    "华强北",
				Province:    "广东省",
				City:        "深圳市",
				District:    "福田区",
				Address:     "华强北路100号",
				Time:        trackTime,
				Description: "有人在华强北看到过",
				IsKeyPoint:  true,
				Lat:         22.5431,
				Lng:         114.0579,
			},
			wantErr: false,
			expectedResp: func(t *testing.T, resp *dto.MissingPersonTrackResponse) {
				assert.NotEmpty(t, resp.ID)
				assert.Equal(t, mp.ID, resp.MissingPersonID)
				assert.Equal(t, reporter.ID, resp.ReporterID)
				assert.Equal(t, "华强北", resp.Location)
				assert.Equal(t, "广东省", resp.Province)
				assert.Equal(t, "深圳市", resp.City)
				assert.Equal(t, "福田区", resp.District)
				assert.Equal(t, "华强北路100号", resp.Address)
				assert.Equal(t, "有人在华强北看到过", resp.Description)
				assert.True(t, resp.IsKeyPoint)
				assert.Equal(t, 22.5431, resp.Lat)
				assert.Equal(t, 114.0579, resp.Lng)
				assert.Equal(t, "pending", resp.Status)
			},
		},
		{
			name:       "add track for non-existing person",
			personID:   "non-existing-id",
			reporterID: reporter.ID,
			req: &dto.CreateMissingPersonTrackRequest{
				Location: "测试地点",
			},
			wantErr: true,
			errMsg:  "not found",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			resp, err := service.AddTrack(testutil.Context(), tt.personID, tt.req, tt.reporterID)
			if tt.wantErr {
				assert.Error(t, err)
				assert.ErrorIs(t, err, ErrMissingPersonNotFound)
				return
			}
			require.NoError(t, err)
			require.NotNil(t, resp)
			tt.expectedResp(t, resp)
		})
	}
}

func TestMissingPersonAppService_GetTracks(t *testing.T) {
	service, tdb := setupMissingPersonTest(t)
	defer tdb.Close()

	// 创建测试数据
	org := &entity.Organization{
		BaseEntity: entity.BaseEntity{ID: "test-org-id"},
		Name:       "测试组织",
		Code:       "TEST001",
		Type:       entity.OrgTypeCity,
	}
	testutil.MustCreate(t, tdb.DB, org)

	reporter := &entity.User{
		BaseEntity: entity.BaseEntity{ID: "reporter-id"},
		Nickname:   "报告人",
		Phone:      "13800138000",
		Role:       entity.RoleVolunteer,
		Status:     entity.UserStatusActive,
		OrgID:      org.ID,
	}
	reporter.SetPassword("password123")
	testutil.MustCreate(t, tdb.DB, reporter)

	mp := &entity.MissingPerson{
		BaseEntity:   entity.BaseEntity{ID: "mp-tracks"},
		CaseNo:       "CASE-20240101-0001",
		Name:         "多轨迹人员",
		Gender:       "male",
		MissingTime:  time.Now(),
		ContactName:  "联系人",
		ContactPhone: "13900139000",
		ReporterID:   reporter.ID,
		OrgID:        org.ID,
		Status:       entity.MissingStatusMissing,
	}
	testutil.MustCreate(t, tdb.DB, mp)

	// 添加多条轨迹
	tracks := []*entity.MissingPersonTrack{
		{
			BaseEntity:      entity.BaseEntity{ID: "track-1"},
			MissingPersonID: mp.ID,
			ReporterID:      reporter.ID,
			Location:        "地点1",
			Time:            time.Date(2024, 1, 20, 10, 0, 0, 0, time.UTC),
			Description:     "描述1",
			Status:          "pending",
		},
		{
			BaseEntity:      entity.BaseEntity{ID: "track-2"},
			MissingPersonID: mp.ID,
			ReporterID:      reporter.ID,
			Location:        "地点2",
			Time:            time.Date(2024, 1, 21, 14, 0, 0, 0, time.UTC),
			Description:     "描述2",
			Status:          "pending",
		},
	}

	for _, track := range tracks {
		testutil.MustCreate(t, tdb.DB, track)
	}

	resp, err := service.GetTracks(testutil.Context(), mp.ID)
	require.NoError(t, err)
	assert.Equal(t, 2, len(resp))
}

func TestMissingPersonAppService_GetStats(t *testing.T) {
	service, tdb := setupMissingPersonTest(t)
	defer tdb.Close()

	// 创建测试数据
	org := &entity.Organization{
		BaseEntity: entity.BaseEntity{ID: "test-org-id"},
		Name:       "测试组织",
		Code:       "TEST001",
		Type:       entity.OrgTypeCity,
	}
	testutil.MustCreate(t, tdb.DB, org)

	reporter := &entity.User{
		BaseEntity: entity.BaseEntity{ID: "reporter-id"},
		Nickname:   "报告人",
		Phone:      "13800138000",
		Role:       entity.RoleVolunteer,
		Status:     entity.UserStatusActive,
		OrgID:      org.ID,
	}
	reporter.SetPassword("password123")
	testutil.MustCreate(t, tdb.DB, reporter)

	// 创建不同状态的走失人员
	persons := []*entity.MissingPerson{
		{
			BaseEntity:   entity.BaseEntity{ID: "mp-1"},
			CaseNo:       "CASE-20240101-0001",
			Name:         "人员1",
			Gender:       "male",
			MissingTime:  time.Now(),
			ContactName:  "联系人",
			ContactPhone: "13900139001",
			ReporterID:   reporter.ID,
			OrgID:        org.ID,
			Status:       entity.MissingStatusMissing,
		},
		{
			BaseEntity:   entity.BaseEntity{ID: "mp-2"},
			CaseNo:       "CASE-20240101-0002",
			Name:         "人员2",
			Gender:       "female",
			MissingTime:  time.Now(),
			ContactName:  "联系人",
			ContactPhone: "13900139002",
			ReporterID:   reporter.ID,
			OrgID:        org.ID,
			Status:       entity.MissingStatusSearching,
		},
		{
			BaseEntity:   entity.BaseEntity{ID: "mp-3"},
			CaseNo:       "CASE-20240101-0003",
			Name:         "人员3",
			Gender:       "male",
			MissingTime:  time.Now(),
			ContactName:  "联系人",
			ContactPhone: "13900139003",
			ReporterID:   reporter.ID,
			OrgID:        org.ID,
			Status:       entity.MissingStatusFound,
		},
		{
			BaseEntity:   entity.BaseEntity{ID: "mp-4"},
			CaseNo:       "CASE-20240101-0004",
			Name:         "人员4",
			Gender:       "female",
			MissingTime:  time.Now(),
			ContactName:  "联系人",
			ContactPhone: "13900139004",
			ReporterID:   reporter.ID,
			OrgID:        org.ID,
			Status:       entity.MissingStatusReunited,
		},
	}

	for _, p := range persons {
		testutil.MustCreate(t, tdb.DB, p)
	}

	stats, err := service.GetStats(testutil.Context())
	require.NoError(t, err)
	require.NotNil(t, stats)

	// Verify status counts
	assert.Equal(t, int64(4), stats.Total)
	assert.Equal(t, int64(1), stats.Missing)
	assert.Equal(t, int64(1), stats.Searching)
	assert.Equal(t, int64(1), stats.Found)
	assert.Equal(t, int64(1), stats.Reunited)
	assert.Equal(t, int64(0), stats.Closed)

	// Note: Time-based stats (TodayNew, WeekNew, MonthNew) depend on SQLite date handling
	// which may work differently with GORM's time.Time serialization.
	// The key status counts above are the primary focus of this test.
}

func TestMissingPersonAppService_Search(t *testing.T) {
	service, tdb := setupMissingPersonTest(t)
	defer tdb.Close()

	// 创建测试数据
	org := &entity.Organization{
		BaseEntity: entity.BaseEntity{ID: "test-org-id"},
		Name:       "测试组织",
		Code:       "TEST001",
		Type:       entity.OrgTypeCity,
	}
	testutil.MustCreate(t, tdb.DB, org)

	reporter := &entity.User{
		BaseEntity: entity.BaseEntity{ID: "reporter-id"},
		Nickname:   "报告人",
		Phone:      "13800138000",
		Role:       entity.RoleVolunteer,
		Status:     entity.UserStatusActive,
		OrgID:      org.ID,
	}
	reporter.SetPassword("password123")
	testutil.MustCreate(t, tdb.DB, reporter)

	// 创建走失人员
	persons := []*entity.MissingPerson{
		{
			BaseEntity:   entity.BaseEntity{ID: "mp-1"},
			CaseNo:       "CASE-20240101-0001",
			Name:         "张三",
			Gender:       "male",
			Description:  "穿着一件红色外套",
			Features:     "脸上有疤痕",
			Clothes:      "红色外套",
			MissingTime:  time.Now(),
			ContactName:  "联系人1",
			ContactPhone: "13900139001",
			ReporterID:   reporter.ID,
			OrgID:        org.ID,
			Status:       entity.MissingStatusMissing,
		},
		{
			BaseEntity:   entity.BaseEntity{ID: "mp-2"},
			CaseNo:       "CASE-20240101-0002",
			Name:         "李四",
			Gender:       "female",
			Description:  "穿着蓝色衣服",
			Features:     "戴眼镜",
			MissingTime:  time.Now(),
			ContactName:  "联系人2",
			ContactPhone: "13900139002",
			ReporterID:   reporter.ID,
			OrgID:        org.ID,
			Status:       entity.MissingStatusMissing,
		},
	}

	for _, p := range persons {
		testutil.MustCreate(t, tdb.DB, p)
	}

	tests := []struct {
		name         string
		keyword      string
		expectedLen  int
		expectedName string
	}{
		{
			name:         "search by name",
			keyword:      "张三",
			expectedLen:  1,
			expectedName: "张三",
		},
		{
			name:         "search by description",
			keyword:      "红色外套",
			expectedLen:  1,
			expectedName: "张三",
		},
		{
			name:         "search by features",
			keyword:      "疤痕",
			expectedLen:  1,
			expectedName: "张三",
		},
		{
			name:        "search with no match",
			keyword:     "不存在的名字",
			expectedLen: 0,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			resp, err := service.Search(testutil.Context(), tt.keyword, 1, 10)
			require.NoError(t, err)
			require.NotNil(t, resp)
			assert.Equal(t, tt.expectedLen, len(resp.List))
			if tt.expectedName != "" && len(resp.List) > 0 {
				assert.Equal(t, tt.expectedName, resp.List[0].Name)
			}
		})
	}
}

func TestMissingPersonAppService_AssignToUser(t *testing.T) {
	_, tdb := setupMissingPersonTest(t)
	defer tdb.Close()

	// 创建测试数据
	org := &entity.Organization{
		BaseEntity: entity.BaseEntity{ID: "test-org-id"},
		Name:       "测试组织",
		Code:       "TEST001",
		Type:       entity.OrgTypeCity,
	}
	testutil.MustCreate(t, tdb.DB, org)

	reporter := &entity.User{
		BaseEntity: entity.BaseEntity{ID: "reporter-id"},
		Nickname:   "报告人",
		Phone:      "13800138000",
		Email:      "reporter_unique@test.com",
		WxOpenID:   "wx_openid_reporter_unique",
		Role:       entity.RoleVolunteer,
		Status:     entity.UserStatusActive,
		OrgID:      org.ID,
	}
	reporter.SetPassword("password123")
	testutil.MustCreate(t, tdb.DB, reporter)

	assignee := &entity.User{
		BaseEntity: entity.BaseEntity{ID: "assignee-id"},
		Nickname:   "被分配人",
		Phone:      "13800138001",
		Email:      "assignee_unique@test.com",
		WxOpenID:   "wx_openid_assignee_unique",
		Role:       entity.RoleManager,
		Status:     entity.UserStatusActive,
		OrgID:      org.ID,
	}
	assignee.SetPassword("password123")
	testutil.MustCreate(t, tdb.DB, assignee)

	// 创建走失人员
	mp := &entity.MissingPerson{
		BaseEntity:   entity.BaseEntity{ID: "mp-assign"},
		CaseNo:       "CASE-20240101-0001",
		Name:         "待分配人员",
		Gender:       "male",
		MissingTime:  time.Now(),
		ContactName:  "联系人",
		ContactPhone: "13900139000",
		ReporterID:   reporter.ID,
		OrgID:        org.ID,
		Status:       entity.MissingStatusMissing,
	}
	testutil.MustCreate(t, tdb.DB, mp)

	// 验证初始状态没有被分配
	var initial entity.MissingPerson
	testutil.MustFind(t, tdb.DB, &initial, "id = ?", mp.ID)
	assert.Nil(t, initial.AssignedTo)

	// 执行分配 - 直接通过 repository 分配
	mp.AssignTo(assignee.ID)
	err := tdb.DB.Save(mp).Error
	require.NoError(t, err)

	// 验证分配成功
	var updated entity.MissingPerson
	testutil.MustFind(t, tdb.DB, &updated, "id = ?", mp.ID)
	require.NotNil(t, updated.AssignedTo)
	assert.Equal(t, assignee.ID, *updated.AssignedTo)
}
