// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Snowitty-Re/CNtunyuan/internal/application/service"
	"github.com/Snowitty-Re/CNtunyuan/internal/config"
	domainService "github.com/Snowitty-Re/CNtunyuan/internal/domain/service"
	"github.com/Snowitty-Re/CNtunyuan/internal/infrastructure/auth"
	"github.com/Snowitty-Re/CNtunyuan/internal/infrastructure/cache"
	"github.com/Snowitty-Re/CNtunyuan/internal/infrastructure/database"
	infraRepo "github.com/Snowitty-Re/CNtunyuan/internal/infrastructure/repository"
	"github.com/Snowitty-Re/CNtunyuan/internal/interfaces/http/handler"
	"github.com/Snowitty-Re/CNtunyuan/internal/interfaces/http/middleware"
	"github.com/Snowitty-Re/CNtunyuan/internal/interfaces/http/router"
	"gorm.io/gorm"
)

// Container dependency container
type Container struct {
	Config               *config.Config
	DB                   *gorm.DB
	Cache                cache.Cache
	AuthService          *domainService.AuthService
	UserService          *service.UserAppService
	OrganizationService  *service.OrganizationAppService
	MissingPersonService *service.MissingPersonAppService
	DialectService       *service.DialectAppService
	TaskService          *service.TaskAppService
	AuthHandler          *handler.AuthHandler
	UserHandler          *handler.UserHandler
	OrganizationHandler  *handler.OrganizationHandler
	MissingPersonHandler *handler.MissingPersonHandler
	DialectHandler       *handler.DialectHandler
	TaskHandler          *handler.TaskHandler
	AuthMiddleware       *middleware.AuthMiddleware
	Router               *router.Router
}

// NewContainer 手动创建依赖容器
func NewContainer(cfg *config.Config) (*Container, error) {
	// 创建数据库连接
	db, err := database.NewDatabase(&cfg.Database)
	if err != nil {
		return nil, err
	}

	// 创建缓存
	redisCache, err := cache.NewRedis(&cfg.Redis)
	if err != nil {
		redisCache = nil
	}

	// 创建 Token 服务
	tokenService := auth.NewJWTService(&cfg.JWT, redisCache)

	// 创建仓储
	userRepo := infraRepo.NewUserRepository(db)
	orgRepo := infraRepo.NewOrganizationRepository(db)
	mpRepo := infraRepo.NewMissingPersonRepository(db)
	dialectRepo := infraRepo.NewDialectRepository(db)
	taskRepo := infraRepo.NewTaskRepository(db)

	// 创建领域服务
	authService := domainService.NewAuthService(userRepo, tokenService, redisCache)

	// 创建应用服务
	userService := service.NewUserAppService(userRepo)
	orgService := service.NewOrganizationAppService(orgRepo)
	mpService := service.NewMissingPersonAppService(mpRepo)
	dialectService := service.NewDialectAppService(dialectRepo)
	taskService := service.NewTaskAppService(taskRepo)

	// 创建 HTTP Handler
	authHandler := handler.NewAuthHandler(authService)
	userHandler := handler.NewUserHandler(userService)
	orgHandler := handler.NewOrganizationHandler(orgService)
	mpHandler := handler.NewMissingPersonHandler(mpService)
	dialectHandler := handler.NewDialectHandler(dialectService)
	taskHandler := handler.NewTaskHandler(taskService)
	authMiddleware := middleware.NewAuthMiddleware(authService)

	// 创建路由
	r := router.NewRouter(
		authHandler,
		userHandler,
		orgHandler,
		mpHandler,
		dialectHandler,
		taskHandler,
		authMiddleware,
	)
	r.Setup()

	return &Container{
		Config:               cfg,
		DB:                   db,
		Cache:                redisCache,
		AuthService:          authService,
		UserService:          userService,
		OrganizationService:  orgService,
		MissingPersonService: mpService,
		DialectService:       dialectService,
		TaskService:          taskService,
		AuthHandler:          authHandler,
		UserHandler:          userHandler,
		OrganizationHandler:  orgHandler,
		MissingPersonHandler: mpHandler,
		DialectHandler:       dialectHandler,
		TaskHandler:          taskHandler,
		AuthMiddleware:       authMiddleware,
		Router:               r,
	}, nil
}
