// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"fmt"
	"strings"

	"github.com/Snowitty-Re/CNtunyuan/internal/application/service"
	"github.com/Snowitty-Re/CNtunyuan/internal/config"
	domainService "github.com/Snowitty-Re/CNtunyuan/internal/domain/service"
	"github.com/Snowitty-Re/CNtunyuan/internal/infrastructure/auth"
	"github.com/Snowitty-Re/CNtunyuan/internal/infrastructure/cache"
	"github.com/Snowitty-Re/CNtunyuan/internal/infrastructure/database"
	infraRepo "github.com/Snowitty-Re/CNtunyuan/internal/infrastructure/repository"
	"github.com/Snowitty-Re/CNtunyuan/internal/infrastructure/sms"
	"github.com/Snowitty-Re/CNtunyuan/internal/infrastructure/storage"
	"github.com/Snowitty-Re/CNtunyuan/internal/infrastructure/wechat"
	"github.com/Snowitty-Re/CNtunyuan/internal/interfaces/http/handler"
	"github.com/Snowitty-Re/CNtunyuan/internal/interfaces/http/middleware"
	"github.com/Snowitty-Re/CNtunyuan/internal/interfaces/http/router"
	"github.com/Snowitty-Re/CNtunyuan/internal/task"
	"github.com/Snowitty-Re/CNtunyuan/pkg/logger"
	"gorm.io/gorm"
)

// Container dependency container
type Container struct {
	Config               *config.Config
	DB                   *gorm.DB
	Cache                cache.Cache
	AuthService          *domainService.AuthService
	UserService          *service.UserAppService
	OrganizationService  *service.OrganizationAppService
	MissingPersonService *service.MissingPersonAppService
	DialectService       *service.DialectAppService
	TaskService          *service.TaskAppService
	FileService          *service.FileAppService
	DashboardService     *service.DashboardService
	AuditLogService      *service.AuditLogService
	AuthHandler          *handler.AuthHandler
	UserHandler          *handler.UserHandler
	OrganizationHandler  *handler.OrganizationHandler
	MissingPersonHandler *handler.MissingPersonHandler
	DialectHandler       *handler.DialectHandler
	TaskHandler          *handler.TaskHandler
	UploadHandler        *handler.UploadHandler
	DashboardHandler     *handler.DashboardHandler
	AuditHandler         *handler.AuditHandler
	BootstrapHandler     *handler.BootstrapHandler
	SystemConfigHandler  *handler.SystemConfigHandler
	AuthMiddleware       *middleware.AuthMiddleware
	AuditMiddleware      *middleware.AuditMiddleware
	Router               *router.Router
}

// NewContainer 手动创建依赖容器
func NewContainer(cfg *config.Config) (*Container, error) {
	// 创建数据库连接
	db, err := database.NewDatabase(&cfg.Database)
	if err != nil {
		return nil, fmt.Errorf("数据库连接失败: %w", err)
	}
	if db == nil {
		return nil, fmt.Errorf("数据库连接失败: db 为 nil")
	}

	runtimeCfg, _, err := config.LoadRuntimeOverrides(context.Background(), db, cfg)
	if err != nil {
		return nil, fmt.Errorf("加载数据库配置覆盖失败: %w", err)
	}
	if runtimeCfg != nil {
		cfg = runtimeCfg
		config.SetConfig(cfg)
	}

	// 创建缓存
	redisCache, err := cache.NewRedis(&cfg.Redis)
	if err != nil {
		redisCache = nil
	}

	// 创建 Token 服务
	tokenService, err := auth.NewJWTService(&cfg.JWT, redisCache)
	if err != nil {
		return nil, fmt.Errorf("JWT配置错误: %w", err)
	}

	// 创建微信客户端
	var wechatClient *wechat.Client
	if cfg.WeChat.AppID != "" && cfg.WeChat.AppSecret != "" {
		wechatClient = wechat.NewClient(cfg.WeChat.AppID, cfg.WeChat.AppSecret)
	}

	// 创建存储服务
	var storageService domainService.StorageService
	switch cfg.Storage.Type {
	case "oss":
		// 阿里云OSS存储
		ossStorage, err := storage.NewOSSStorage(&cfg.Storage)
		if err != nil {
			logger.Error("Failed to create OSS storage", logger.Err(err))
			// 降级到本地存储
			storageService = storage.NewLocalStorage(&cfg.Storage)
		} else {
			storageService = ossStorage
			logger.Info("Using OSS storage", logger.String("bucket", cfg.Storage.OSSBucket))
		}
	case "cos":
		// 腾讯云COS存储
		cosStorage, err := storage.NewCOSStorage(&cfg.Storage)
		if err != nil {
			logger.Error("Failed to create COS storage", logger.Err(err))
			// 降级到本地存储
			storageService = storage.NewLocalStorage(&cfg.Storage)
		} else {
			storageService = cosStorage
			logger.Info("Using COS storage", logger.String("bucket", cfg.Storage.COSBucket))
		}
	default:
		storageService = storage.NewLocalStorage(&cfg.Storage)
		logger.Info("Using local storage", logger.String("path", cfg.Storage.LocalPath))
	}

	// 创建仓储
	userRepo := infraRepo.NewUserRepository(db)
	orgRepo := infraRepo.NewOrganizationRepository(db)
	mpRepo := infraRepo.NewMissingPersonRepository(db)
	dialectRepo := infraRepo.NewDialectRepository(db)
	taskRepo := infraRepo.NewTaskRepository(db)
	fileRepo := infraRepo.NewFileRepository(db)
	auditRepo := infraRepo.NewAuditLogRepository(db)
	authzPolicyRepo := infraRepo.NewAuthzPolicyRepository(db)
	notificationRepo := infraRepo.NewSystemNotificationRepository(db)
	authzService := service.NewAuthorizationService(orgRepo, authzPolicyRepo)
	authzService.SetNotificationRepository(notificationRepo)

	// 创建领域服务
	authService := domainService.NewAuthService(userRepo, tokenService, redisCache, wechatClient)

	// 创建短信服务并注入到认证服务
	smsService := sms.NewService(&cfg.SMS, redisCache)
	authService.SetSMSService(smsService)
	authService.SetSecurityConfig(&cfg.Security)

	// 创建应用服务
	userService := service.NewUserAppService(userRepo, taskRepo, mpRepo, orgRepo, authzService)
	orgService := service.NewOrganizationAppService(orgRepo)
	mpService := service.NewMissingPersonAppService(mpRepo, orgRepo, authzService)
	dialectService := service.NewDialectAppService(dialectRepo, userRepo, orgRepo, fileRepo, storageService, authzService)
	taskService := service.NewTaskAppService(taskRepo, userRepo, orgRepo, authzService)
	fileService := service.NewFileAppService(
		fileRepo,
		storageService,
		cfg.Storage.MaxFileSize,
		strings.Split(cfg.Storage.AllowedTypes, ","),
	)
	dashboardService := service.NewDashboardService(
		userRepo,
		orgRepo,
		mpRepo,
		taskRepo,
		dialectRepo,
		fileRepo,
		redisCache,
	)
	healthService := service.NewHealthService(db, redisCache)
	auditLogService := service.NewAuditLogService(auditRepo)

	// 创建 Middleware
	authMiddleware := middleware.NewAuthMiddleware(authService)

	// 创建审计日志中间件（自动记录所有API请求）
	auditMiddleware := middleware.NewAuditMiddleware(auditRepo)

	// 创建 HTTP Handler
	auditHandler := handler.NewAuditHandler(auditLogService)
	authHandler := handler.NewAuthHandler(authService, authMiddleware)
	userHandler := handler.NewUserHandler(userService)
	orgHandler := handler.NewOrganizationHandler(orgService)
	mpHandler := handler.NewMissingPersonHandler(mpService)
	dialectHandler := handler.NewDialectHandler(dialectService)
	taskHandler := handler.NewTaskHandler(taskService)
	uploadHandler := handler.NewUploadHandler(fileService)
	dashboardHandler := handler.NewDashboardHandler(dashboardService)
	bootstrapHandler := handler.NewBootstrapHandler(userRepo, healthService, db)
	systemConfigHandler := handler.NewSystemConfigHandlerWithAuthz(authzService, db)

	// 创建路由
	r := router.NewRouter(
		authHandler,
		userHandler,
		orgHandler,
		mpHandler,
		dialectHandler,
		taskHandler,
		uploadHandler,
		dashboardHandler,
		auditHandler,
		bootstrapHandler,
		systemConfigHandler,
		authMiddleware,
		auditMiddleware,
		healthService,
		redisCache,
	)
	r.Setup()

	// 启动定时任务调度器
	scheduler := task.NewScheduler(taskRepo, mpRepo, userRepo, auditRepo, authzService)
	scheduler.SetDatabaseConfig(&cfg.Database, &cfg.Backup)
	scheduler.SetSystemConfig(&cfg.System)
	if err := scheduler.Start(); err != nil {
		logger.Error("Failed to start task scheduler", logger.Err(err))
	}

	return &Container{
		Config:               cfg,
		DB:                   db,
		Cache:                redisCache,
		AuthService:          authService,
		UserService:          userService,
		OrganizationService:  orgService,
		MissingPersonService: mpService,
		DialectService:       dialectService,
		TaskService:          taskService,
		FileService:          fileService,
		DashboardService:     dashboardService,
		AuditLogService:      auditLogService,
		AuthHandler:          authHandler,
		UserHandler:          userHandler,
		OrganizationHandler:  orgHandler,
		MissingPersonHandler: mpHandler,
		DialectHandler:       dialectHandler,
		TaskHandler:          taskHandler,
		UploadHandler:        uploadHandler,
		DashboardHandler:     dashboardHandler,
		AuditHandler:         auditHandler,
		BootstrapHandler:     bootstrapHandler,
		SystemConfigHandler:  systemConfigHandler,
		AuthMiddleware:       authMiddleware,
		AuditMiddleware:      auditMiddleware,
		Router:               r,
	}, nil
}
