// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Snowitty-Re/CNtunyuan/internal/application/service"
	"github.com/Snowitty-Re/CNtunyuan/internal/config"
	domainService "github.com/Snowitty-Re/CNtunyuan/internal/domain/service"
	"github.com/Snowitty-Re/CNtunyuan/internal/infrastructure/auth"
	"github.com/Snowitty-Re/CNtunyuan/internal/infrastructure/cache"
	"github.com/Snowitty-Re/CNtunyuan/internal/infrastructure/database"
	infraRepo "github.com/Snowitty-Re/CNtunyuan/internal/infrastructure/repository"
	"github.com/Snowitty-Re/CNtunyuan/internal/interfaces/http/handler"
	"github.com/Snowitty-Re/CNtunyuan/internal/interfaces/http/middleware"
	"gorm.io/gorm"
)

// Container dependency container
type Container struct {
	Config         *config.Config
	DB             *gorm.DB
	Cache          cache.Cache
	AuthService    *domainService.AuthService
	UserService    *service.UserAppService
	UserHandler    *handler.UserHandler
	AuthHandler    *handler.AuthHandler
	AuthMiddleware *middleware.AuthMiddleware
}

// NewContainer 手动创建依赖容器（在没有 Wire 生成代码时使用）
func NewContainer(cfg *config.Config) (*Container, error) {
	// 创建数据库连接
	db, err := database.NewDatabase(&cfg.Database)
	if err != nil {
		return nil, err
	}

	// 创建缓存
	redisCache, err := cache.NewRedis(&cfg.Redis)
	if err != nil {
		// 缓存失败不阻止服务启动
		redisCache = nil
	}

	// 创建 Token 服务
	tokenService := auth.NewJWTService(&cfg.JWT, redisCache)

	// 创建仓储
	userRepo := infraRepo.NewUserRepository(db)

	// 创建领域服务
	authService := domainService.NewAuthService(userRepo, tokenService, redisCache)

	// 创建应用服务
	userAppService := service.NewUserAppService(userRepo)

	// 创建 HTTP Handler
	authHandler := handler.NewAuthHandler(authService)
	userHandler := handler.NewUserHandler(userAppService)
	authMiddleware := middleware.NewAuthMiddleware(authService)

	return &Container{
		Config:         cfg,
		DB:             db,
		Cache:          redisCache,
		AuthService:    authService,
		UserService:    userAppService,
		UserHandler:    userHandler,
		AuthHandler:    authHandler,
		AuthMiddleware: authMiddleware,
	}, nil
}
